### PR TITLE
Separate development of starter from the starter itself

### LINKED ISSUE #53: Removing package-lock.json and make repo independent of development
A starter template should ideally not include a lock-file to allow usage of other dependency managers (also instructed in https://github.com/nuxt/starter). Removing that from the repository could get difficult for development, so a branching & CI may need to be setup (happy to look into myself & create a PR when I get time).

_Issue started from https://github.com/sidestream-tech/sidebase/issues/13#issuecomment-1258137528_

### PR DESCRIPTION
**Pull request by ineshbose**
Provides the option to do development on Sidebase while not requiring the environment to be the replica of the starter. This means that while `main` could be the default starter branch, `dev` is where changes are made. Change originally inspired from #53 where lock-file is discussed to be removed.

Branches `main` and `starter/**` are treated as actual starters, so the development files such as `package-lock.json` would be removed. The files to remove can be listed on `exclude-starter.txt`. The pipeline is also triggered on PRs onto these branches!

(also closes #53)

(This is a draft PR. See https://github.com/sidestream-tech/sidebase/issues/53#issuecomment-1259669574)

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] issue checkboxes are all addressed
- [x] manually checked my feature / not applicable
- [x] wrote tests / not applicable
- [x] attached screenshots / not applicable

### CODE REVIEW

**Review by BracketJohn — CHANGES_REQUESTED** [review]
hey @ineshbose,

first of all: thanks for the contribution ❤️ 

I love the idea, one thing I'm worrying about though: How can we ensure that the other "sub-starters" will not become broken due to dependency-resolving not working out?

E.g.: When we develop with `npm` and change the `package.json` + `package-lock.json` and then have CI running we know that `npm i` will run through for everybody.

If we then copy over just the `package.json` and use `pnpm`, we cannot be sure that this will also work without tweaking it. We may need CI for every branch with every package manager we support to ensure that sidebase will keep on being stable, right?

**Comment by ineshbose** [comment]
Thanks for sharing your thoughts @BracketJohn. If I'm not wrong, do you mean that if a starter template were to be updated, how would users locally include those changes? I believe updating a starter isn't the same way as updating a dependency or syncing a fork since the boilerplate is a one-time kickstarter for users to help them take on their own path. So future changes would be only applied to cloners from that point on, while if previous users want to update, it may need to be manually. Think of using a `nuxt/starter` yourself and how an update around that would work - typically those starters aren't updated after establishing the minimum configurated template. But if you're trying to have something like `npx nuxi@latest update --force` for example, even there the migration would need to be manual (such as `defineNuxtConfig` being deprecated RC-10 onwards).

As for dependency resolution, I would think of that to be out of our scope and to be solved by the dependency managers themselves. Of course internally, the team may want to continue using `npm` and `package-lock.json` would remain on `dev`. Perhaps if required - an instruction to delete the lock-file and install again to regenerate it from their preferred dependency manager. With that said, there is an interesting project that kinda resolves the dependency manager problem - https://github.com/antfu/ni. The testing pipeline can make use of it (I can add it to this PR).

Speaking of pipelines, if lock-files are really required, another pipeline can be added to upload different lock-files as artifacts (can also be added to this PR, but personally I don't see the use of this feature). Having the dependency managers as branches also adds much more for the maintainers to handle (also given #13) and the general consensus is usually to not have lock-files in starter templates regardless! 🙂

**Comment by BracketJohn** [comment]
Thanks for the reply (: 

The last part is what I was getting at: We should have lock-files to ensure that the `npm i` actually works out. For projects with a single dependency it may not be necessary, but as we pull in a lot of dev and non-dev deps, we should ensure that the user can always successfully install them. The only way to not accidentally break something (i.e.: it worked with `npm` for us, but it breaks with `pnpm`!) is to include lock-files as far as I know.

> the general consensus is usually to not have lock-files in starter templates regardless! 🙂

I'm willing to not include lock-files though, if you can give a bit of proof for this statement: Where can I find the consensus that not including a lock file in starters is best practice? How do these projects ensure that the project install always works out and doesn't fail in the dep-resolution step?

**Comment by ineshbose** [comment]
I've switched `ci.yaml` to use `ni`.

> The only way to not accidentally break something (i.e.: it worked with `npm` for us, but it breaks with `pnpm`!) is to include lock-files as far as I know. I'm willing to not include lock-files though, if you can give a bit of proof for this statement: Where can I find the consensus that not including a lock file in starters is best practice? How do these projects ensure that the project install always works out and doesn't fail in the dep-resolution step?

I did not know that `pnpm` is breaking. I don't have a concrete proof I'm afraid - it's just the convention I've noticed with boilerplates in my time and experience (obviously also seeing that the `nuxt/starter` README says to not include them). Dependency resolution should be handled by the package managers themselves because that's what they're specialised in, but if one of them is unable to resolve it, that's an issue on our part and I feel could be a separate issue about why/how that's happening - that way I could also add a dev test pipeline for testing if resolution works for all known package managers (I could add it for this, but don't want one PR to start implementing multiple features and be of bigger diff).

**Comment by BracketJohn** [comment]
For documentation: We discussed on discord that this issue is resolved with the introduction of the sidebase cli: 
Just now release the last version (for tonight) 🎊  

The CLI is package manager and dev-file independent and allows to manually configure what modules you want to use, just use the new sidebase CLI:
```
npm create sidebase@latest
```

You can still use the full sidebase stack by choosing `Cheviot` as a stack on the first CLI question. This also works with `pnpm` and `yarn`. The CLI will guide you through a sidebase app creation process:
image


Please checkout the full docs if you want to learn more: https://sidebase.io/sidebase/welcome

**Pull request closed without merging**
