### PR TITLE
Removed historie packages and upgraded to RC 13

### PR DESCRIPTION
**Pull request by zoey-kaiser**
After removing everything related to historie I recieved the following error:

```
 ERROR  Cannot find package 'pathe' imported from /Users/zoey/Documents/Development/SideStream/sidebase/sidebase/node_modules/@nuxtjs/tailwindcss/dist/module.mjs                                                         14:42:17

  at new NodeError (node:internal/errors:387:5)
  at packageResolve (node:internal/modules/esm/resolve:951:9)
  at moduleResolve (node:internal/modules/esm/resolve:1000:20)
  at defaultResolve (node:internal/modules/esm/resolve:1214:11)
  at nextResolve (node:internal/modules/esm/loader:165:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)
```

This confuses me a lot, as I do not know why @nuxtjs/tailwindcss would be linked with historie. The exact package that causes this error to be thrown is [@historie/plugin-nuxt](https://www.npmjs.com/package/@histoire/plugin-nuxt).

### CODE REVIEW

**Comment by BracketJohn** [comment]
you did also bump the nuxt tailwind module - could this be the cause? 

Do you think we can get this merged this week? Would be awesome to be ready for nuxt stable which will release next week Wednesday (:

**Comment by zoey-kaiser** [comment]
> you did also bump the nuxt tailwind module - could this be the cause?

Yes I have! https://github.com/sidebase/sidebase/blob/dc4f12fbef87f716f45551e3a76c2e74319f3b9c/package.json#L30

**Comment by BracketJohn** [comment]
> Yes I have! 

I'm saying that this may be the problem :D I would hnestly only remove histoire packages in this PR + do the nuxt bump and that's it!

**Comment by zoey-kaiser** [comment]
> I'm saying that this may be the problem :D I would hnestly only remove histoire packages in this PR + do the nuxt bump and that's it!

I reverted the change, however the issue still sadly persists!

**Comment by valiafetisov** [comment]
> I do not know why @nuxtjs/tailwindcss would be linked with historie

It might be that `historie` or some of its dependencies used `pathe` package, which is no longer present. Have you tried (as a quick fix) adding `pathe` to dev dependencies?

**Comment by zoey-kaiser** [comment]
> It might be that `historie` or some of its dependencies used `pathe` package, which is no longer present. Have you tried (as a quick fix) adding `pathe` to dev dependencies?

adding pathe did fix the issue. However I would like to know:

- Do we need to install it seperatly? Why does it not get installed together with tailwindcss?
- Why are some tests failing now (backend server tests) even tho I changed nothing about the code there?

**Comment by valiafetisov** [comment]
Glad it worked

> Do we need to install it seperatly? Why does it not get installed together with tailwindcss?

It can be a failure of npm to properly resolve shared dependencies during removal of `historie`. I would:

1. Uninstall `pathe` from dev dependencies
2. Try to reinstall `@nuxt/tailwindcss` and `tailwindcss` as well as the `nuxt-parse` – all packages that have missing packages as their dependencies

Maybe you can also search for `npm`-related issues on package removal and available solutions

**Pull request closed without merging**
